// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsKUYR4Y5wVQ67P4binFkxDAcl86zYOw',
    appId: '1:39800414771:web:df3f6b9834841b29183946',
    messagingSenderId: '39800414771',
    projectId: 'hostel-management-83521',
    authDomain: 'hostel-management-83521.firebaseapp.com',
    storageBucket: 'hostel-management-83521.appspot.com',
    measurementId: 'G-JKWJR7XFNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5I1Hc1TrDuFdANuFvRI6Y89ZRN7_vbU8',
    appId: '1:39800414771:android:28e2bb4cac0e7a31183946',
    messagingSenderId: '39800414771',
    projectId: 'hostel-management-83521',
    storageBucket: 'hostel-management-83521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26Bauy2I0jDM3aoG644e_qxbhsscSIIU',
    appId: '1:39800414771:ios:79cdf6f7a8a00001183946',
    messagingSenderId: '39800414771',
    projectId: 'hostel-management-83521',
    storageBucket: 'hostel-management-83521.appspot.com',
    iosClientId: '39800414771-tkdnva8q8ndcp361gf8ealsil0gcrrj0.apps.googleusercontent.com',
    iosBundleId: 'com.vamsidhar.hostely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26Bauy2I0jDM3aoG644e_qxbhsscSIIU',
    appId: '1:39800414771:ios:79cdf6f7a8a00001183946',
    messagingSenderId: '39800414771',
    projectId: 'hostel-management-83521',
    storageBucket: 'hostel-management-83521.appspot.com',
    iosClientId: '39800414771-tkdnva8q8ndcp361gf8ealsil0gcrrj0.apps.googleusercontent.com',
    iosBundleId: 'com.vamsidhar.hostely',
  );
}
